// 校园商家数据
const CAMPUS_DATA = {
  siteName: "智慧校园生活平台",
  campusName: "阳光大学",
  slogan: "一站式校园生活服务，让每一天更美好",

  // 商家分类
  categories: [
    { id: "all", name: "全部", icon: "fas fa-th-large", color: "#667eea" },
    { id: "canteen", name: "校园餐厅", icon: "fas fa-utensils", color: "#f093fb" },
    { id: "supermarket", name: "超市便利店", icon: "fas fa-shopping-cart", color: "#4facfe" },
    { id: "clinic", name: "医务室", icon: "fas fa-heartbeat", color: "#43e97b" },
    { id: "telecom", name: "营业厅", icon: "fas fa-mobile-alt", color: "#fa709a" },
    { id: "swimming", name: "游泳馆", icon: "fas fa-swimmer", color: "#a18cd1" },
    { id: "gym", name: "体育馆", icon: "fas fa-dumbbell", color: "#fbc2eb" },
    { id: "library", name: "图书馆", icon: "fas fa-book", color: "#84fab0" },
    { id: "print", name: "打印复印", icon: "fas fa-print", color: "#fccb90" },
    { id: "bank", name: "银行服务", icon: "fas fa-university", color: "#a1c4fd" },
    { id: "cafe", name: "咖啡奶茶", icon: "fas fa-coffee", color: "#f6d365" },
    { id: "barbershop", name: "理发店", icon: "fas fa-cut", color: "#ff9a9e" }
  ],

  // 商家列表
  merchants: [
    // ===== 校园餐厅 =====
    {
      id: 1,
      name: "学苑第一餐厅",
      category: "canteen",
      categoryName: "校园餐厅",
      rating: 4.5,
      reviews: 1286,
      image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400&h=300&fit=crop",
      tags: ["中式快餐", "经济实惠", "早餐供应"],
      address: "学苑路1号 · 一食堂一楼",
      hours: "06:30 - 21:00",
      phone: "010-8888-1001",
      description: "学苑第一餐厅是校内最大的食堂，提供丰富多样的中式菜品，涵盖川菜、粤菜、鲁菜等多种风味。价格亲民，是同学们日常就餐的首选之地。",
      services: ["堂食", "打包外带", "校园配送", "包间预订"],
      featured: true,
      hotIndex: 98
    },
    {
      id: 2,
      name: "清真风味餐厅",
      category: "canteen",
      categoryName: "校园餐厅",
      rating: 4.7,
      reviews: 856,
      image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop",
      tags: ["清真美食", "牛肉拉面", "烤馕"],
      address: "学苑路1号 · 二食堂二楼",
      hours: "07:00 - 20:30",
      phone: "010-8888-1002",
      description: "清真风味餐厅提供正宗的清真美食，包括手工拉面、烤馕、大盘鸡等特色菜品，环境整洁，深受少数民族同学喜爱。",
      services: ["堂食", "打包外带", "校园配送"],
      featured: false,
      hotIndex: 85
    },
    {
      id: 3,
      name: "教工餐厅",
      category: "canteen",
      categoryName: "校园餐厅",
      rating: 4.8,
      reviews: 423,
      image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=400&h=300&fit=crop",
      tags: ["精致菜品", "环境优雅", "师生可用"],
      address: "行政楼一楼",
      hours: "11:00 - 13:30 / 17:00 - 19:30",
      phone: "010-8888-1003",
      description: "教工餐厅提供精致的中式菜品和西式简餐，环境优雅安静，菜品质量上乘，师生均可持校园卡消费。",
      services: ["堂食", "打包外带", "包间预订"],
      featured: true,
      hotIndex: 76
    },
    {
      id: 4,
      name: "美食广场",
      category: "canteen",
      categoryName: "校园餐厅",
      rating: 4.3,
      reviews: 1567,
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop",
      tags: ["各地小吃", "夜宵", "烧烤"],
      address: "学苑路3号 · 三食堂",
      hours: "10:00 - 23:00",
      phone: "010-8888-1004",
      description: "美食广场汇聚全国各地特色小吃，从麻辣烫到烤冷面，从煎饼果子到臭豆腐，应有尽有。晚间还提供夜宵服务。",
      services: ["堂食", "打包外带", "校园配送", "夜宵"],
      featured: true,
      hotIndex: 95
    },

    // ===== 超市便利店 =====
    {
      id: 5,
      name: "校园便利超市",
      category: "supermarket",
      categoryName: "超市便利店",
      rating: 4.4,
      reviews: 934,
      image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&h=300&fit=crop",
      tags: ["日用百货", "零食饮料", "学习用品"],
      address: "学生活动中心一楼",
      hours: "07:00 - 23:00",
      phone: "010-8888-2001",
      description: "校园便利超市商品种类齐全，涵盖零食饮料、日用百货、学习用品等，支持校园卡和移动支付，购物便捷。",
      services: ["到店购物", "校园配送", "校园卡支付"],
      featured: true,
      hotIndex: 90
    },
    {
      id: 6,
      name: "鲜果时光",
      category: "supermarket",
      categoryName: "超市便利店",
      rating: 4.6,
      reviews: 567,
      image: "https://images.unsplash.com/photo-1610832968500-5a898661e022?w=400&h=300&fit=crop",
      tags: ["新鲜水果", "鲜榨果汁", "健康零食"],
      address: "学苑路2号",
      hours: "08:00 - 22:00",
      phone: "010-8888-2002",
      description: "鲜果时光专营新鲜水果和鲜榨果汁，每日新鲜到货，还提供水果拼盘和果篮定制服务，健康美味两不误。",
      services: ["到店购物", "校园配送", "果篮定制"],
      featured: false,
      hotIndex: 72
    },
    {
      id: 7,
      name: "24小时便利店",
      category: "supermarket",
      categoryName: "超市便利店",
      rating: 4.2,
      reviews: 445,
      image: "https://images.unsplash.com/photo-1586787468163-b2d0bb5b3e3e?w=400&h=300&fit=crop",
      tags: ["24小时营业", "应急用品", "速食"],
      address: "宿舍区入口处",
      hours: "24小时营业",
      phone: "010-8888-2003",
      description: "全天候营业的便利店，满足同学们任何时间段的购物需求，提供速食、饮料、日用品等应急商品。",
      services: ["到店购物", "24小时营业", "校园卡支付"],
      featured: false,
      hotIndex: 68
    },

    // ===== 医务室 =====
    {
      id: 8,
      name: "校医院",
      category: "clinic",
      categoryName: "医务室",
      rating: 4.3,
      reviews: 789,
      image: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=400&h=300&fit=crop",
      tags: ["全科诊疗", "体检服务", "医保报销"],
      address: "校园南路 · 医疗中心",
      hours: "08:00 - 17:30（急诊24小时）",
      phone: "010-8888-3001",
      description: "校医院提供全科诊疗、预防保健、健康体检等服务，设有内科、外科、口腔科、眼科等科室，支持医保报销。",
      services: ["全科诊疗", "疫苗接种", "健康体检", "心理咨询", "急诊服务", "医保报销"],
      featured: true,
      hotIndex: 80
    },
    {
      id: 9,
      name: "校园药房",
      category: "clinic",
      categoryName: "医务室",
      rating: 4.5,
      reviews: 345,
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop",
      tags: ["常用药品", "医疗器械", "保健用品"],
      address: "医疗中心一楼",
      hours: "08:00 - 21:00",
      phone: "010-8888-3002",
      description: "校园药房提供常用药品、医疗器械和保健用品，药品价格优惠，部分药品可使用医保卡购买。",
      services: ["药品零售", "医疗器械", "健康咨询"],
      featured: false,
      hotIndex: 65
    },

    // ===== 营业厅 =====
    {
      id: 10,
      name: "中国移动营业厅",
      category: "telecom",
      categoryName: "营业厅",
      rating: 4.1,
      reviews: 234,
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop",
      tags: ["话费充值", "套餐办理", "宽带安装"],
      address: "学生活动中心二楼",
      hours: "09:00 - 18:00",
      phone: "010-8888-4001",
      description: "中国移动校园营业厅提供话费充值、套餐变更、宽带安装、手机维修等一站式通信服务，还有专属学生优惠套餐。",
      services: ["话费充值", "套餐办理", "宽带安装", "手机维修", "SIM卡补办"],
      featured: false,
      hotIndex: 60
    },
    {
      id: 11,
      name: "中国电信营业厅",
      category: "telecom",
      categoryName: "营业厅",
      rating: 4.0,
      reviews: 189,
      image: "https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=400&h=300&fit=crop",
      tags: ["校园宽带", "流量套餐", "电信业务"],
      address: "学生活动中心二楼",
      hours: "09:00 - 18:00",
      phone: "010-8888-4002",
      description: "中国电信校园营业厅提供宽带办理、套餐咨询、故障报修等服务，校园宽带速度快、价格优。",
      services: ["宽带办理", "套餐咨询", "故障报修", "SIM卡补办"],
      featured: false,
      hotIndex: 55
    },

    // ===== 游泳馆 =====
    {
      id: 12,
      name: "校园游泳馆",
      category: "swimming",
      categoryName: "游泳馆",
      rating: 4.7,
      reviews: 678,
      image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&h=300&fit=crop",
      tags: ["标准泳池", "游泳课程", "水质优良"],
      address: "体育中心西区",
      hours: "06:30 - 21:00",
      phone: "010-8888-5001",
      description: "校园游泳馆拥有50米标准泳池和25米教学泳池，水质达到国家一级标准。提供游泳课程培训、救生员培训等服务。",
      services: ["自由泳", "游泳培训", "救生培训", "泳具租赁", "淋浴更衣"],
      featured: true,
      hotIndex: 88
    },

    // ===== 体育馆 =====
    {
      id: 13,
      name: "综合体育馆",
      category: "gym",
      categoryName: "体育馆",
      rating: 4.6,
      reviews: 534,
      image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop",
      tags: ["健身器材", "羽毛球", "篮球"],
      address: "体育中心主楼",
      hours: "06:00 - 22:00",
      phone: "010-8888-5002",
      description: "综合体育馆配备先进的健身器材，还有羽毛球馆、篮球馆、乒乓球馆等场地可供预约使用。定期举办健身课程和体育活动。",
      services: ["健身锻炼", "场地预约", "健身课程", "器材租赁", "体质测试"],
      featured: true,
      hotIndex: 86
    },
    {
      id: 14,
      name: "瑜伽工作室",
      category: "gym",
      categoryName: "体育馆",
      rating: 4.8,
      reviews: 312,
      image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop",
      tags: ["瑜伽课程", "冥想放松", "塑形美体"],
      address: "体育中心三楼",
      hours: "08:00 - 21:00",
      phone: "010-8888-5003",
      description: "专业瑜伽工作室提供哈他瑜伽、流瑜伽、阴瑜伽等多种课程，小班教学，专业教练指导，帮助同学们放松身心、塑造体形。",
      services: ["瑜伽课程", "私教课程", "冥想课程", "瑜伽垫租赁"],
      featured: false,
      hotIndex: 70
    },

    // ===== 图书馆 =====
    {
      id: 15,
      name: "中心图书馆",
      category: "library",
      categoryName: "图书馆",
      rating: 4.9,
      reviews: 2345,
      image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&h=300&fit=crop",
      tags: ["自习空间", "电子资源", "学术氛围"],
      address: "校园中轴线 · 图书馆大楼",
      hours: "07:00 - 22:30",
      phone: "010-8888-6001",
      description: "中心图书馆藏书百万册，设有自习区、研讨室、电子阅览室等功能区域。提供图书借阅、文献检索、论文查重等学术服务。",
      services: ["图书借阅", "自习空间", "研讨室预约", "文献检索", "论文查重", "电子资源"],
      featured: true,
      hotIndex: 97
    },

    // ===== 打印复印 =====
    {
      id: 16,
      name: "文印中心",
      category: "print",
      categoryName: "打印复印",
      rating: 4.2,
      reviews: 876,
      image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400&h=300&fit=crop",
      tags: ["打印复印", "证件照", "装订"],
      address: "图书馆一楼大厅",
      hours: "08:00 - 21:00",
      phone: "010-8888-7001",
      description: "文印中心提供黑白/彩色打印、复印、扫描、装订、证件照拍摄等服务，支持在线下单和自助打印。",
      services: ["打印复印", "证件照拍摄", "文件装订", "在线下单", "自助打印"],
      featured: false,
      hotIndex: 75
    },
    {
      id: 17,
      name: "快印自助站",
      category: "print",
      categoryName: "打印复印",
      rating: 4.0,
      reviews: 234,
      image: "https://images.unsplash.com/photo-1568667256549-094345857637?w=400&h=300&fit=crop",
      tags: ["自助打印", "24小时", "快捷方便"],
      address: "宿舍区一楼大厅",
      hours: "24小时自助",
      phone: "010-8888-7002",
      description: "快印自助站提供24小时自助打印服务，支持手机上传文件、扫码打印，方便快捷，随时随地满足打印需求。",
      services: ["自助打印", "扫码打印", "手机上传"],
      featured: false,
      hotIndex: 62
    },

    // ===== 银行服务 =====
    {
      id: 18,
      name: "工商银行校园支行",
      category: "bank",
      categoryName: "银行服务",
      rating: 4.3,
      reviews: 456,
      image: "https://images.unsplash.com/photo-1556742393-d75f468bfcb0?w=400&h=300&fit=crop",
      tags: ["存取款", "转账汇款", "银行卡办理"],
      address: "行政楼一楼",
      hours: "09:00 - 17:00（工作日）",
      phone: "010-8888-8001",
      description: "工商银行校园支行提供存取款、转账汇款、银行卡办理、助学贷款等金融服务，设有ATM自助服务区。",
      services: ["存取款", "转账汇款", "银行卡办理", "助学贷款", "ATM服务"],
      featured: false,
      hotIndex: 58
    },
    {
      id: 19,
      name: "建设银行ATM",
      category: "bank",
      categoryName: "银行服务",
      rating: 4.0,
      reviews: 234,
      image: "https://images.unsplash.com/photo-1590201710266-7e5e1a468beb?w=400&h=300&fit=crop",
      tags: ["ATM取款", "自助服务", "24小时"],
      address: "学生活动中心一楼大厅",
      hours: "24小时自助",
      phone: "010-8888-8002",
      description: "建设银行ATM自助服务区，提供24小时存取款、转账、余额查询等自助银行服务。",
      services: ["ATM取款", "转账", "余额查询"],
      featured: false,
      hotIndex: 50
    },

    // ===== 咖啡奶茶 =====
    {
      id: 20,
      name: "拾光咖啡",
      category: "cafe",
      categoryName: "咖啡奶茶",
      rating: 4.7,
      reviews: 678,
      image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop",
      tags: ["精品咖啡", "阅读空间", "WiFi"],
      address: "图书馆一楼西侧",
      hours: "08:00 - 22:00",
      phone: "010-8888-9001",
      description: "拾光咖啡是一家精品咖啡店，提供手冲咖啡、意式咖啡、茶饮等。店内环境温馨，有免费WiFi，是学习和休闲的好去处。",
      services: ["堂食", "外带", "校园配送", "WiFi"],
      featured: true,
      hotIndex: 92
    },
    {
      id: 21,
      name: "茶百道奶茶",
      category: "cafe",
      categoryName: "咖啡奶茶",
      rating: 4.5,
      reviews: 1234,
      image: "https://images.unsplash.com/photo-1558857563-b371033873b8?w=400&h=300&fit=crop",
      tags: ["奶茶果茶", "网红饮品", "价格实惠"],
      address: "学苑路2号",
      hours: "09:00 - 22:00",
      phone: "010-8888-9002",
      description: "茶百道提供各类奶茶、果茶、奶盖茶等饮品，口味丰富，价格实惠，是同学们课余时间的好选择。",
      services: ["堂食", "外带", "校园配送"],
      featured: true,
      hotIndex: 94
    },
    {
      id: 22,
      name: "蜜雪冰城",
      category: "cafe",
      categoryName: "咖啡奶茶",
      rating: 4.3,
      reviews: 1567,
      image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop",
      tags: ["冰淇淋", "柠檬水", "超值优惠"],
      address: "宿舍区入口处",
      hours: "09:30 - 22:30",
      phone: "010-8888-9003",
      description: "蜜雪冰城以超值的价格提供美味的冰淇淋、柠檬水、奶茶等饮品，是校园里最受欢迎的高性价比饮品店。",
      services: ["堂食", "外带", "校园配送"],
      featured: false,
      hotIndex: 89
    },

    // ===== 理发店 =====
    {
      id: 23,
      name: "校园造型理发店",
      category: "barbershop",
      categoryName: "理发店",
      rating: 4.1,
      reviews: 345,
      image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=300&fit=crop",
      tags: ["学生优惠", "男女理发", "烫染"],
      address: "学苑路3号",
      hours: "09:00 - 20:00",
      phone: "010-8888-10001",
      description: "校园造型理发店提供男女理发、烫发、染发等服务，持校园卡可享学生优惠价格，环境整洁，手艺精湛。",
      services: ["男士理发", "女士理发", "烫发", "染发", "护发"],
      featured: false,
      hotIndex: 56
    }
  ],

  // 公告信息
  announcements: [
    { id: 1, title: "游泳馆暑期特惠活动", content: "6月1日至8月31日，游泳馆月卡8折优惠！", date: "2024-06-01", type: "activity" },
    { id: 2, title: "图书馆延长开放时间通知", content: "考试周期间（6月15日-6月30日），图书馆开放时间延长至23:30。", date: "2024-06-10", type: "notice" },
    { id: 3, title: "新商家入驻：瑞幸咖啡", content: "瑞幸咖啡即将入驻学生活动中心一楼，敬请期待！", date: "2024-06-15", type: "new" },
    { id: 4, title: "美食广场烧烤节", content: "每周五、周六晚，美食广场举办烧烤主题活动，更有优惠套餐等你来！", date: "2024-06-20", type: "activity" }
  ]
};
